apiVersion: v1
kind: Service
metadata:
    name: hustoj
    namespace: hustoj
    labels:
        service: hustoj
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
